name: my first wf
on: 
    push:
    workflow_dispatch:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome msg
              run: echo "hello data eng"